/**
 * MCP Tool Schemas for Mongrate
 *
 * Defines the tools available via MCP for interacting with migrations.
 */

export const TOOL_SCHEMAS = {
  // Migration listing and status
  list_migrations: {
    name: "list_migrations",
    description:
      "List all migrations with their current status. Returns migration ID, name, status, and creation date.",
    inputSchema: {
      type: "object" as const,
      properties: {
        status: {
          type: "string",
          enum: [
            "pending",
            "cloning",
            "planning",
            "plan_ready",
            "executing",
            "completed",
            "failed",
          ],
          description: "Filter by migration status",
        },
        limit: {
          type: "number",
          description: "Maximum number of migrations to return (default: 20)",
        },
      },
    },
  },

  get_migration_status: {
    name: "get_migration_status",
    description:
      "Get detailed status of a specific migration including config, status, current agent, and results.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID to get status for",
        },
      },
      required: ["migrationId"] as const,
    },
  },

  get_migration_plan: {
    name: "get_migration_plan",
    description:
      "Get the migration plan generated by Agent 1. Contains table mappings, indexes, and transformation rules.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID",
        },
      },
      required: ["migrationId"] as const,
    },
  },

  get_migration_logs: {
    name: "get_migration_logs",
    description:
      "Get logs from a migration. Returns timestamped entries from both planning and execution agents.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID",
        },
        limit: {
          type: "number",
          description: "Number of log entries to return (default: 50)",
        },
        level: {
          type: "string",
          enum: ["info", "warn", "error"],
          description: "Filter logs by level",
        },
      },
      required: ["migrationId"] as const,
    },
  },

  // Migration control
  start_planning: {
    name: "start_planning",
    description:
      "Start the planning agent (Agent 1) for a migration. Analyzes the codebase and creates a migration plan.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID to plan",
        },
      },
      required: ["migrationId"] as const,
    },
  },

  start_execution: {
    name: "start_execution",
    description:
      "Start the execution agent (Agent 2) for a migration. Requires a completed plan from Agent 1.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID to execute",
        },
      },
      required: ["migrationId"] as const,
    },
  },

  // Repository browsing
  browse_files: {
    name: "browse_files",
    description: "Browse files in the cloned repository for a migration. Lists directory contents.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID",
        },
        path: {
          type: "string",
          description: "Directory path relative to repo root (default: root)",
        },
      },
      required: ["migrationId"] as const,
    },
  },

  read_file: {
    name: "read_file",
    description: "Read a file from the cloned repository.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID",
        },
        filePath: {
          type: "string",
          description: "File path relative to repo root",
        },
      },
      required: ["migrationId", "filePath"] as const,
    },
  },

  // Migration management
  create_migration: {
    name: "create_migration",
    description: "Create a new migration job. Requires repository URL and connection strings.",
    inputSchema: {
      type: "object" as const,
      properties: {
        name: {
          type: "string",
          description: "Name for this migration",
        },
        repoUrl: {
          type: "string",
          description: "GitHub repository URL to migrate",
        },
        branch: {
          type: "string",
          description: "Branch to clone (default: main)",
        },
        postgresUrl: {
          type: "string",
          description: "PostgreSQL connection string (optional)",
        },
        mongoUrl: {
          type: "string",
          description: "Target MongoDB connection string",
        },
      },
      required: ["name", "repoUrl", "mongoUrl"] as const,
    },
  },

  delete_migration: {
    name: "delete_migration",
    description: "Delete a migration and its associated data.",
    inputSchema: {
      type: "object" as const,
      properties: {
        migrationId: {
          type: "string",
          description: "The migration ID to delete",
        },
      },
      required: ["migrationId"] as const,
    },
  },
} as const;

export type ToolName = keyof typeof TOOL_SCHEMAS;
